v1.1.3a

diff --git a/linux/jpeg2webp b/linux/jpeg2webp
--- a/linux/jpeg2webp
+++ b/linux/jpeg2webp
@@ -89,8 +89,8 @@ fi
 # pragma DEPENDENCIES
 # pragma 1. ImageMagick
 start_spinner "1. Making sure ImageMagick is installed."
-if ! which magick > /dev/null; then
-    printf "ImageMagick is not installed. To install it, please enter your password if required.\n"
+if ! dpkg -l | grep imagemagick > /dev/null; then
+    printf "\n    ImageMagick is not installed. To install it, please enter your password if required."
     sudo apt update
     sudo apt install imagemagick
 fi
@@ -98,8 +98,8 @@ stop_spinner $?
 
 # pragma 2. coreutils
 start_spinner "2. Making sure coreutils is installed."
-if ! which coreutils > /dev/null; then
-    printf "Coreutils is not installed. To install it, please enter your password if required.\n"
+if ! dpkg -l | grep coreutils > /dev/null; then
+    printf "\n    Coreutils is not installed. To install it, please enter your password if required.\n"
     sudo apt-get update -y
     sudo apt-get install -y coreutils
 fi
@@ -107,8 +107,8 @@ stop_spinner $?
 
 # pragma 3. Zenity
 start_spinner "3. Making sure Zenity is installed."
-if ! which zenity > /dev/null; then
-    printf "Zenity is not installed. To install it, please enter your password if required.\n"
+if ! dpkg -l | grep zenity > /dev/null; then
+    printf "\n    Zenity is not installed. To install it, please enter your password if required.\n"
     sudo apt-get update -y
     sudo apt-get install -y zenity
 fi
@@ -169,7 +169,7 @@ function album_cover() {
 }
 
 function random_album_cover() {
-    COVER_FILE_NAME=$(find . -maxdepth 1 | gshuf -n 1 | cut -c 3-)
+    COVER_FILE_NAME=$(find . -maxdepth 1 | shuf -n 1 | cut -c 3-)
 }
 
 while :
